#ifndef SF_SECRETS_H
#define SF_SECRETS_H

#include <glib-object.h>
#include <gio/gio.h>

#define SF_TYPE_SECRETS_PLUGIN_INFO (sf_secrets_manager_get_type())

typedef struct SfSecretsPluginInfo_ SfSecretsPluginInfo;
typedef struct SfSecretsSecretIdentifier_ SfSecretsSecretIdentifier;

typedef enum SfSecretsUserInteractionMode_ {
	SF_SECRETS_USER_INTERACTION_MODE_PREVENT = 0,
	SF_SECRETS_USER_INTERACTION_MODE_SYSTEM,
	SF_SECRETS_USER_INTERACTION_MODE_APPLICATION
} SfSecretsUserInteractionMode;

typedef enum SfSecretsAccessControlMode_ {
	SF_SECRETS_ACCESS_CONTROL_MODE_OWNER_ONLY = 0,
	SF_SECRETS_ACCESS_CONTROL_MODE_SYSTEM_ACCESS,
	SF_SECRETS_ACCESS_CONTROL_MODE_NONE
} SfSecretsAccessControlMode;

typedef enum SfSecretsDeviceUnlockSemantic_ {
	SF_SECRETS_DEVICE_UNLOCK_SEMANTIC_KEEP_UNLOCKED = 0,
	SF_SECRETS_DEVICE_UNLOCK_SEMANTIC_VERIFY_LOCK,
	SF_SECRETS_DEVICE_UNLOCK_SEMANTIC_RELOCK,
} SfSecretsDeviceUnlockSemantic;

typedef enum SfSecretsPluginState_ {
	SF_SECRETS_PLUGIN_STATE_UNKNOWN   = 0,
	SF_SECRETS_PLUGIN_STATE_AVAILABLE = 1 << 0,
	SF_SECRETS_PLUGIN_STATE_MASTER_UNLOCKED = 1 << 1,
	SF_SECRETS_PLUGIN_STATE_PLUGIN_UNLOCKED = 1 << 2,
	SF_SECRETS_PLUGIN_STATE_PLUGIN_SUPPORTS_LOCKING = 1 << 2,
	SF_SECRETS_PLUGIN_STATE_PLUGIN_SUPPORTS_SET_LOCK_CODE = 1 << 2,
} SfSecretsPluginState;

typedef enum SfSecretsError_ {
        SF_SECRETS_ERROR_NO = 0,
        SF_SECRETS_ERROR_UNKNOWN = 2,
        SF_SECRETS_ERROR_SERIALIZATION = 3,
        SF_SECRETS_ERROR_DAEMON = 5,
        SF_SECRETS_ERROR_DISCOVERY = 6,

        SF_SECRETS_ERROR_PERMISSIONS = 10,
        SF_SECRETS_ERROR_INCORRECT_AUTHENTICATION_CODE,
        SF_SECRETS_ERROR_AUTHENTICATION_TIMEOUT,
        SF_SECRETS_ERROR_OPERATION_NOT_SUPPORTED,
        SF_SECRETS_ERROR_OPERATION_REQUIRES_USER_INTERACTION,
        SF_SECRETS_ERROR_OPERATION_REQUIRES_APPLICATION_USER_INTERACTION,
        SF_SECRETS_ERROR_OPERATION_REQUIRES_SYSTEM_USER_INTERACTION,
        SF_SECRETS_ERROR_SECRET_MANAGER_NOT_INITIALIZED,

        SF_SECRETS_ERROR_SECRETS_DAEMON_REQUEST_PID = 20,
        SF_SECRETS_ERROR_SECRETS_DAEMON_REQUEST_QUEUE_FULL,
        SF_SECRETS_ERROR_SECRETS_DAEMON_LOCKED,
        SF_SECRETS_ERROR_SECRETS_DAEMON_NOT_LOCKED,

        SF_SECRETS_ERROR_SECRETS_PLUGIN_ENCRYPTION = 30,
        SF_SECRETS_ERROR_SECRETS_PLUGIN_DECRYPTION,
        SF_SECRETS_ERROR_SECRETS_PLUGIN_KEY_DERIVATION,
        SF_SECRETS_ERROR_SECRETS_PLUGIN_IS_LOCKED,

        SF_SECRETS_ERROR_INVALID_SECRET = 40,
        SF_SECRETS_ERROR_INVALID_SECRET_IDENTIFIER,
        SF_SECRETS_ERROR_INVALID_FILTER,
        SF_SECRETS_ERROR_INVALID_COLLECTION,
        SF_SECRETS_ERROR_INVALID_EXTENSION_PLUGIN,
        SF_SECRETS_ERROR_INVALID_APPLICATION_ID,
        SF_SECRETS_ERROR_COLLECTION_ALREADY_EXISTS,
        SF_SECRETS_ERROR_SECRET_ALREADY_EXISTS,

        SF_SECRETS_ERROR_COLLECTION_IS_LOCKED = 60,
        SF_SECRETS_ERROR_COLLECTION_IS_BUSY,

        SF_SECRETS_ERROR_DATABASE_QUERY = 70,
        SF_SECRETS_ERROR_DATABASE_TRANSACTION,
        SF_SECRETS_ERROR_DATABASE,

        SF_SECRETS_ERROR_INTERACTION_SERVICE_UNKNOWN = 80,
        SF_SECRETS_ERROR_INTERACTION_SERVICE_UNAVAILABLE,
        SF_SECRETS_ERROR_INTERACTION_SERVICE_REQUEST_INVALID,
        SF_SECRETS_ERROR_INTERACTION_SERVICE_REQUEST_FAILED,
        SF_SECRETS_ERROR_INTERACTION_SERVICE_REQUEST_BUSY,
        SF_SECRETS_ERROR_INTERACTION_SERVICE_RESPONSE_INVALID,

        SF_SECRETS_ERROR_INTERACTION_VIEW_UNAVAILABLE = 90,
        SF_SECRETS_ERROR_INTERACTION_VIEW_REQUEST,
        SF_SECRETS_ERROR_INTERACTION_VIEW_PARENT,
        SF_SECRETS_ERROR_INTERACTION_VIEW_CHILD,
        SF_SECRETS_ERROR_INTERACTION_VIEW,
        SF_SECRETS_ERROR_INTERACTION_VIEW_USER_CANCELED,

        SF_SECRETS_ERROR_NETWORK = 98,
        SF_SECRETS_ERROR_NETWORK_SSL = 99,
        SF_SECRETS_ERROR_HTTP_CONTINUE = 100,
        SF_SECRETS_ERROR_HTTP_SWITCHING_PROTOCOL = 101,
        SF_SECRETS_ERROR_HTTP_OK = 200,
        SF_SECRETS_ERROR_HTTP_CREATED = 201,
        SF_SECRETS_ERROR_HTTP_ACCEPTED = 202,
        SF_SECRETS_ERROR_HTTP_NON_AUTHORITATIVE_INFORMATION = 203,
        SF_SECRETS_ERROR_HTTP_NO_CONTENT = 204,
        SF_SECRETS_ERROR_HTTP_RESET_CONTENT = 205,
        SF_SECRETS_ERROR_HTTP_PARTIAL_CONTENT = 206,
        SF_SECRETS_ERROR_HTTP_MULTIPLE_CHOICE = 300,
        SF_SECRETS_ERROR_HTTP_MOVED_PERMANENTLY = 301,
        SF_SECRETS_ERROR_HTTP_FOUND = 302,
        SF_SECRETS_ERROR_HTTP_SEE_OTHER = 303,
        SF_SECRETS_ERROR_HTTP_NOT_MODIFIED = 304,
        SF_SECRETS_ERROR_HTTP_USE_PROXY = 305,
        SF_SECRETS_ERROR_HTTP_UNUSED = 306,
        SF_SECRETS_ERROR_HTTP_TEMPORARY_REDIRECT = 307,
        SF_SECRETS_ERROR_HTTP_PERMANENT_REDIRECT = 308,
        SF_SECRETS_ERROR_HTTP_BAD_REQUEST = 400,
        SF_SECRETS_ERROR_HTTP_UNAUTHORIZED = 401,
        SF_SECRETS_ERROR_HTTP_PAYMENT_REQUIRED = 402,
        SF_SECRETS_ERROR_HTTP_FORBIDDEN = 403,
        SF_SECRETS_ERROR_HTTP_NOT_FOUND = 404,
        SF_SECRETS_ERROR_HTTP_METHOD_NOT_ALLOWED = 405,
        SF_SECRETS_ERROR_HTTP_NOT_ACCEPTABLE = 406,
        SF_SECRETS_ERROR_HTTP_PROXY_AUTHENTICATION_REQUIRED = 407,
        SF_SECRETS_ERROR_HTTP_REQUEST_TIMEOUT = 408,
        SF_SECRETS_ERROR_HTTP_CONFLICT = 409,
        SF_SECRETS_ERROR_HTTP_GONE = 410,
        SF_SECRETS_ERROR_HTTP_LENGTH_REQUIRED = 411,
        SF_SECRETS_ERROR_HTTP_PRECONDITION_FAILED = 412,
        SF_SECRETS_ERROR_HTTP_PAYLOAD_TOO_LARGE = 413,
        SF_SECRETS_ERROR_HTTP_URI_TOO_LONG = 414,
        SF_SECRETS_ERROR_HTTP_UNSUPPORTED_MEDIA_TYPE = 415,
        SF_SECRETS_ERROR_HTTP_REQUEST_RANGE_NOT_SATISFIABLE = 416,
        SF_SECRETS_ERROR_HTTP_EXPECTATION_FAILED = 417,
        SF_SECRETS_ERROR_HTTP_MISDIRECTED_REQUEST = 421,
        SF_SECRETS_ERROR_HTTP_UPGRADE_REQUIRED = 426,
        SF_SECRETS_ERROR_HTTP_PRECONDITION_REQUIRED = 428,
        SF_SECRETS_ERROR_HTTP_TOO_MANY_REQUESTS = 429,
        SF_SECRETS_ERROR_HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
        SF_SECRETS_ERROR_HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = 451,
        SF_SECRETS_ERROR_HTTP_INTERNAL_SERVER = 500,
        SF_SECRETS_ERROR_HTTP_NOT_IMPLEMENTED = 501,
        SF_SECRETS_ERROR_HTTP_BAD_GATEWAY = 502,
        SF_SECRETS_ERROR_HTTP_SERVICE_UNAVAILABLE = 503,
        SF_SECRETS_ERROR_HTTP_GATEWAY_TIMEOUT = 504,
        SF_SECRETS_ERROR_HTTP_VERSION_NOT_SUPPORTED = 505,
        SF_SECRETS_ERROR_HTTP_VARIANT_ALSO_NEGOTIATES = 506,
        SF_SECRETS_ERROR_HTTP_INSUFFICIENT_STORAGE = 507,
        SF_SECRETS_ERROR_HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511,

        SF_SECRETS_ERROR_OTHER = 1024,
} SfSecretsError;

struct SfSecretsPluginInfo_ {
	gchar *display_name;
	gchar *name;
	int version;
	SfSecretsPluginState state;
};

struct SfSecretsSecretIdentifier_ {
	gchar *name;
	gchar *collection_name;
	gchar *storage_plugin_name;
};

void sf_secrets_plugin_info_free(SfSecretsPluginInfo *info);

#endif
